### ISSUE TITLE
Please release latest version to npm

### ISSUE THREAD

**Issue by stereokai** [klumba12/vscroll#14]
Please release latest version to npm - or either just the version without the postinstall script

**Comment by klumba12** [comment]
Hello,

How do you install vscroll? 
Do you add this to package.json? `"vscroll": "https://github.com/klumba12/vscroll"`
If so invoke `npm i` , also if you want to freeze version you can use tagging

**Comment by stereokai** [comment]
@klumba12 We use `npm install` (from package.json at `"ng-vscroll": "0.9.0"` (latest))

See for yourself:
[https://unpkg.com/ng-vscroll@latest/package.json](https://unpkg.com/ng-vscroll@latest/package.json) - this is the latest version of `ng-vscroll` published to npm:
```
  "scripts": {
    "postinstall": "bower install", <--- this happens after every install
    "test": "gulp test"
  },
```

Bower is deprecated and is in the process of being phased out. We want to remove it from our project but we can't because of `ng-vscroll`

You merged my pull request but didn't release it to npm yet. Please release a new version to npm with the `postinstall` fix.

Thanks for understanding 😃 👍

**Comment by stereokai** [comment]
@klumba12 hello?
